name: Flyway â€” Staging

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: staging
    env:
      DB_HOST: ${{ secrets.STAGING_DB_HOST }}
      DB_PORT: ${{ secrets.STAGING_DB_PORT }}
      DB_USER: ${{ secrets.STAGING_DB_USER }}
      DB_PASS: ${{ secrets.STAGING_DB_PASS }}
      DB_NAME: ${{ secrets.STAGING_DB_NAME }}
      DB_SCHEMA: ${{ secrets.STAGING_DB_SCHEMA }}   # optional

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Flyway migrate (staging) using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/db/flyway/sql:/flyway/sql \
            flyway/flyway:11.15.0 \
            -url="jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require" \
            -user="${DB_USER}" \
            -password="${DB_PASS}" \
            -configFiles=./db/flyway/conf/flyway_staging.conf \
            migrate